version: "3.7"
services:
  postgres13:
    platform: linux/amd64
    image: postgres:13
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5432:5432
