name: Continuous Integration
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run linters
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.41

  # Enable when there are unit tests
  #  unit:
  #    runs-on: ubuntu-latest
  #    strategy:
  #      matrix:
  #        go: ['1.16']
  #    steps:
  #      - uses: actions/checkout@v2.3.4
  #      - uses: actions/setup-go@v2
  #        with:
  #          go-version: ${{ matrix.go }}
  #      - uses: actions/cache@v2.1.6
  #        with:
  #          path: ~/go/pkg/mod
  #          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
  #          restore-keys: |
  #            ${{ runner.os }}-go-
  #      - name: Run tests
  #        run: go test -race ./internal/template/...

  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.16"]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run go generate
        run: go generate ./...
      - name: Check generated files
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "you need to run 'go generate ./...' and commit the changes"
            echo "$status"
            exit 1
          fi

  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.16"]
    services:
      postgres12:
        image: postgres:12.3
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run integration tests
        working-directory: internal/integration
        run: go test -race -count=2 ./...
